clear_files: true
output_folder: "./conservation_analysis"
database_filekey: "../../data/example_orthogroup_database/human_odb_groups/database_key.json"
table_file: "./table.csv"
hit_sequence_params:
  hit_sequence_search_method: "search"
idr_params:
  find_idrs: true
  # idr_map_file: "./idr_map.json"
  iupred_cutoff: 0.4
  gap_merge_threshold: 10
  idr_min_length: 8
# precalculated_aln_conservation_score_keys:
  # - "aln_property_entropy"
filter_params:
  min_num_orthos: 20
new_score_methods:
  aln_asym_sum_of_pairs:
    matrix_name: "EDSSMat50_max_off_diagonal_norm"
    gap_frac_cutoff: 0.2
    overwrite: true
multilevel_plot_params:
  score_key: "aln_property_entropy"
  score_type: "zscore"
table_annotation_params:
  score_key_for_table: "aln_property_entropy"
  motif_regex: "P.P.E"
  levels:
    # - "Eukaryota"
    # - "Metazoa"
    - "Vertebrata"
    - "Tetrapoda"
    # - "Mammalia"
clean_analysis_files: false
