output_folder: "./conservation_analysis"
database_filekey: "../../data/example_orthogroup_database_merged_version/human_odb_groups/database_key.json"
table_file: "./table.csv"
hit_sequence_params:
  hit_sequence_search_method: "search"
idr_params:
  find_idrs: true
  # idr_map_file: "./idr_map.json"
  iupred_cutoff: 0.4
  gap_merge_threshold: 10
  idr_min_length: 8
precalculated_aln_conservation_score_keys:
  - "property_entropy"
filter_params:
  min_num_orthos: 20
# new_score_methods:
#   property_entropy:
#     matrix_name: "EDSSMat50_max_off_diagonal_norm"
#     gap_frac_cutoff: 0.2
clear_files: false
